config/routes.rb
Rails.application.routes.draw do

  root 'pages#welcome'
  get 'portfolio' => 'pages#portfolio'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def welcome
	end

	def portfolio
	end
	
	def about
	end
	
	def contact
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
	<title>Portfolio</title>
	<link href="https://fonts.googleapis.com/css?family=Roboto:100,300,500,700" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>

<body>
	<div class="header">

		<div class="row">
			<div class="col-md-3">
				<p>Brad Spitz</p>
			</div>
		    <div class="col-md-9">
				<ul class="menu">
					<li><%= link_to 'Welcome', root_path %></li>
					<li><%= link_to 'Portfolio', portfolio_path %></li>
					<li><%= link_to 'About', about_path %></li>
					<li><%= link_to 'Contact', contact_path %></li>
				</ul>
			</div>
		</div>

	</div>

	<%= yield %>

	<div class="footer">

		<div class="row">
			<ul class="menu">
				<li><a href="#">GitHub</a></li>
				<li><a href="#">LinkedIn</a></li>
				<li><a href="#">Twitter</a></li>
			</ul>
		</div>
		<div class="row">
			<p>&copy; 2016 Brad Spitz</p>
		</div>

	</div>

</body>
</html>

app/views/pages/about.html.erb
<div class="supporting">
	<div class="container about-container">
		<%= image_tag 'pic.jpg', :class => 'round-img' %>
		<h1>My Story</h1>
		<p>It was a dark and stormy night.  I was alone and surrounded by program specifications as far as the eye could see.  Suddenly, one of the specifications charged forward.  I deftly called upon my vast development knowledge and coded a robust solution, but the specification was unfazed.  "Implementation Not Supported," it called back mockingly.  I looked around in exasperation.  "What do you mean nobody uses Fortran anymore?!" I shouted, to no one in particular.</p>
		<p>Oh wait, not that kind of story?  Fine...</p>
		<p>I have a fascination with technology going back to my days as a kid in suburban Indiana writing silly BASIC programs on my parents' Commodore 64 in the late 80s.  That passion led me to Purdue University, where I obtained a bachelor's degree in computer engineering in 2003.  My focus at Purdue was in software engineering, and I learned a great deal about program design and coding in a wide variety of programming languages (including, yes, Fortran).</p>
		<p>Unfortunately, 2003 was not a kind year to computer engineers just entering the workforce, and I found myself enrolling in the Indianapolis campus of the Indiana University School of Law that same year.  I graduated from law school <i>summa cum laude</i> in 2006, and since then I have worked as a patent attorney in the software, semiconductor, and wireless communication fields.  In 2009, I relocated to San Diego to be near local clients and have made it my home ever since.</p>
		<p>Today, I split my time between patent law and brushing up on my software development skills, with the goal of ultimately entering software development full time.  While patent law has been a rewarding career for me, I miss the days of working on my own ideas rather than just writing about someone else's.  With my legal knowledge and experience combined with my skills as a developer, I will bring a unique perspective to the world of software design.</p>
		<p class="disclaimer">Disclaimer: No part of this website is intended to be interpreted as attorney advertisement.  I am not accepting new legal clients at this time.</p>
	</div>
</div>

app/views/pages/contact.html.erb
<div class="supporting">
	<div class="container contact-container">
		<h1>Contact Me</h1>
		<ul>
			<a href="#"><%= image_tag 'github.svg', :class => 'icon' %></a>
			<a href="#"><%= image_tag 'linkedin.svg', :class => 'icon' %></a>
			<a href="#"><%= image_tag 'twitter.svg', :class => 'icon' %></a>
			<a href="#"><%= image_tag 'facebook.svg', :class => 'icon' %></a>
			<a href="#"><%= image_tag 'email.svg', :class => 'icon' %></a>
		</ul>
		<a href="http://flaticon.com" class="attribution">Icons designed by SimpleIcon and Freepik from Flaticon</a>
	</div>
</div>

app/views/pages/portfolio.html.erb
<script>
	jQuery(document).ready(function($) {
		$('.slider').unslider(
			{
				infinite: true,
				keys: false,
				arrows: true
			});
	});
</script>

<div class="main">
	<div class="container slider-container">
		<div class="slider">
			<ul>
				<li><a href="http://bdspitz-nearme.herokuapp.com"><%= image_tag 'screen1.png', :class => 'img-responsive' %></a></li>
				<li><a href="http://bdspitz-bass.herokuapp.com"><%= image_tag 'screen2.png', :class => 'img-responsive' %></a></li>
				<li><a href="http://bdspitz-books.herokuapp.com"><%= image_tag 'screen3.png', :class => 'img-responsive' %></a></li>
				<li><a href="http://bdspitz-stories.herokuapp.com"><%= image_tag 'screen4.png', :class => 'img-responsive' %></a></li>
			</ul>
		</div>
	</div>
</div>

<div class="supporting">
	<div class="container">
		<div class="row">
			<div class="col-md-6">
				<a href="http://bdspitz-nearme.herokuapp.com">
					<%= image_tag 'screen1.png', :class => 'img-responsive' %>
					<h3>NearMe</h3>
					<p>Point of interest locator using the MediaWiki API.  Built in AngularJS with the Leaflet library.</p>
				</a>
			</div>
			<div class="col-md-6">
				<a href="http://bdspitz-nearme.herokuapp.com">
					<%= image_tag 'screen2.png', :class => 'img-responsive' %>
					<h3>Bass Music</h3>
					<p>Album/track viewer for a music cataloging application.  Built in Rails.</p>
				</a>
			</div>
			<div class="col-md-6">
				<a href="http://bdspitz-nearme.herokuapp.com">
					<%= image_tag 'screen3.png', :class => 'img-responsive' %>
					<h3>Bookmarks</h3>
					<p>Book best-seller list/review aggregator application.  Built in Rails.</p>
				</a>
			</div>
			<div class="col-md-6">
				<a href="http://bdspitz-stories.herokuapp.com">
					<%= image_tag 'screen4.png', :class => 'img-responsive' %>
					<h3>Stories</h3>
					<p>Product website for a photo aggregator application with signup form and associated database.  Built in Rails.</p>
				</a>
			</div>
		</div>
	</div>
</div>				

app/views/pages/welcome.html.erb
<div class="main">
	<div class="jumbotron">
		<div class="container-fluid">
			<h1>My name is Brad Spitz and I create solutions that make ideas into reality.</h1>
			<%= link_to 'View My Work', portfolio_path, :class => 'btn' %>
		</div>
	</div>
</div>